### ISSUE TITLE
Make determination on use of multiple lines when importing multiple named exports

### ISSUE THREAD

**Issue by notmessenger** [softlayer/ember-style-guide#21]

**Comment by erangeles** [comment]
"use of multiple lines", can you exemplify what you mean. I subscribe to the es6 way of doing [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) . with multiple members of a module being imported it should all be in one line.

**Comment by notmessenger** [comment]
Taking from that example, "use of multiple lines" would mean:

```
import {
    member1,
    member2 as alias2,
    [...]
} from 'module-name';
```

**Comment by notmessenger** [comment]
The question becomes one of line length.  Since we enforce a max line length - https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#line-lengths - it is possible that an import statement could exceed it.  When that occurs then there are two options: 1) break it into multiple lines importing from the same file, or 2) breaking it into multiple lines for a single import statement, such as in the example in the previous comment.

At the very least we should set a guideline for which of these approaches should be used over the other. Which then leads to the question of whether it is only when line length is exceeded or if we want to follow it all of the time regardless.

The thinking being that you can get into one pattern of doing things, without have to access when to make the switch to the other.  Or when a single entry from the multi-line entry is removed - you now need to condense the statement to a single line if it falls under the line length criteria.

The goal is to make these guidelines as easy, painless, and thought-free to use without becoming bogged down with decision points every time you're just trying to write code.

**Comment by erangeles** [comment]
Every single import statement I've seen has been one line, however you case increases readability. I can be swayed either way on this but leaning towards more of a 'if line length exceeded' approach. My main argument with one line import statements is that the convention seems to be one line in most of the JS community(no source, just anecdotal evidence) and it would be a lower barrier to entry for people to contribute to our repos since they are used to importing using one line.

**Comment by notmessenger** [comment]
A suggestion offered by Jeroen is the following:

```
import ( * } from 'utils';
import { member1, member2 as alias2, member3,
    member4 as alias4, } from 'module-name';
import { some as other } from 'here';
```

moving to a new line, and indenting it, whenever the line length limit is reached.

**Comment by erangeles** [comment]
from a readability perspective I disagree with that approach. rather leverage multiple lines to increase readability then to just serve the purpose of addressing line length.

**Comment by azizpunjani** [comment]
How about just having multiple import statements if line length is too long? Probably has a tiny performance penalty but should be negligible.

```javascript
import ( * } from 'utils';
import { member1, member2 as alias2 } from 'module-name'; 
import { member3, member4 as alias4 } from 'module-name';
import { some as other } from 'here';
```

**Comment by erangeles** [comment]
I concur with aziz.

**Comment by joshforisha** [comment]
I would prefer a simple rule of allowing literal arrays and objects to be on a single line up to a point of reduced readability, which I'd place around 80 characters. We have a custom ESLint rule, "max-literal-len" to define this functionality.

The "multiple import" approach seems odd, and potentially problematic by being too easy to import the same reference.

**Comment by notmessenger** [comment]
Are you saying @joshforisha that all one one line until hit 80 and then it has be to become one per line, such as with the https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#newlines rule?

**Comment by joshforisha** [comment]
@notmessenger Yes, although it doesn't *have* to remain on a single line till then; the point is that the majority of short literal objects, like `import` statements, don't have to be broken down, so they shouldn't have to be.
