### ISSUE TITLE
Reconsider no trailing commas

### ISSUE THREAD

**Issue by notmessenger** [softlayer/ember-style-guide#25]
https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#commas

As of ES5, trailing commas are allowed.  Since we are coding in ES6 and ES7 syntax, and are using transpilation, consider the following items:

* Which version of IE (or other browsers) have issues with trailing commas?
* Does the transpiler correct for this in our preferred configuration?
* Assuming the previous two items align with our desires, do we want to change this rule?

**Comment by alxyuu** [comment]
I am of the opinion that this should not be changed, even if it is allowed. Even though it is supported, there is no recommendation to use trailing commas. From what I can tell, the only added benefit is being able to rearrange elements while coding without having to add/remove a comma.

Also, JSON does not support trailing commas. Adding trailing commas to the style guide would result in a disconnect between the style used in JS vs JSON.

Adding trailing commas only alienates older browsers and causes irregularities with little to no benefit.
