### ISSUE TITLE
Evaluate semicolons after function exports

### ISSUE THREAD

**Issue by alxyuu** [softlayer/ember-style-guide#32]
Currently, sl-eslint does not allow for semicolons after functions. As a result, exporting like so triggers an error:
```js
export function foo() {
};
```

However, all other exports are followed by semicolons, and semicolons after functions is accepted syntax.

Should we allow for semicolons after function exports?

**Comment by notmessenger** [comment]
Making @joshforisha aware of this

**Comment by joshforisha** [comment]
I'd say no.

Semicolons serve to separate statements from one another. A function declaration is not a statement, and is defined to not need a semicolon. The export keyword simply makes the following statement or declaration available to consumers of the module. So, the semicolon does absolutely nothing in these cases.

**Comment by alxyuu** [comment]
I am okay with this.

However, just to make sure, if we are exporting functions, do we always want to export function declarations, i.e.
```js
export function foo() {
};
```

and not function expressions?
```js
export const foo = function() {
};
```

For function expressions, there should definitely be a semicolon, as explained here:
http://stackoverflow.com/questions/1834642/why-should-i-use-a-semicolon-after-every-function-in-javascript

If we are going to enforce only exporting function declarations, then I'm okay with no semicolons.

**Comment by joshforisha** [comment]
I agree with function expressions needing semicolons, but I don't see any advantage to using them over declarations.
