### ISSUE TITLE
Why do const variables need to be grouped at the top of their block?

### ISSUE THREAD

**Issue by joshforisha** [softlayer/ember-style-guide#7]
Variables created with `const` have the same restrictions and rules as `let` variables do, so why force `const` variables to the top of their scope while `let` can go anywhere?

As an aside to this question, ESLint has an option to suggest using `const` over `let` (or `var`) for variables that aren't changed throughout their usage. While we don't necessarily need to enable that option, it seems like it would be useful long-term. With the option enabled, we'd potentially also have to move the variable to the top of its block when recommended to use `const` in place of a `let`, which seems like a silly, arbitrary change.

**Comment by notmessenger** [comment]
Agreed.  https://github.com/softlayer/ember-style-guide/commit/77ef13778ae24c381ba5daac8f94eb81f23852b8 made this change
