### ISSUE TITLE
Is Collection the only accepted suffix for collection names?

### ISSUE THREAD

**Issue by joshforisha** [softlayer/ember-style-guide#9]
In the *Naming Conventions* section of javascript.md, this rule is outlined:

```md
SHOULD append Collection to the name of sets of items
```

I understand the need to clarify that one variable is a collection of another type, but the section is not clear enough about the allowed ways this can be done. The language denotes `Collection` as the preferred suffix, but that seems overly verbose for many cases; most of which a simple plural name would suffice. I assume the example of `hardware` and `hardwareCollection` is used to show a case where `hardwares` is nonsensical, but why not `hardwareItems`? Even the comment explaining the variable uses "hardware items" to describe it.

If other values are allowed, maybe that section should just have more detail about the reasoning behind the soft rule.

**Comment by notmessenger** [comment]
Resolved by https://github.com/softlayer/ember-style-guide/pull/10
